[tool.poetry]
name = "ffgetter"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
isort = "^5.12.0"
mock = "^5.0.1"
pycodestyle = "^2.10.0"
python = ">=3.9,<4.0"
requests = "^2.28.2"
requests-oauthlib = "^1.3.1"

[tool.isort]
multi_line_output = 9
line_length = 256

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
