[tool.poetry]
name = "ffgetter"
version = "1.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
coverage = "^7.2.2"
cryptography = "^39.0.2"
freezegun = "^1.2.2"
isort = "^5.12.0"
jinja2 = "^3.1.2"
mock = "^5.0.1"
plyer = "^2.1.0"
pycodestyle = "^2.10.0"
pyppeteer = "^1.0.2"
python = ">=3.9,<4.0"
requests = "^2.28.2"
requests-html = "^0.10.0"
requests-oauthlib = "^1.3.1"

[tool.isort]
multi_line_output = 9
line_length = 256

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
